[project]
name = "millstone"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "black>=25.1.0",
    "flake8>=7.3.0",
    "fsspec>=2025.5.1",
    "gcsfs>=2025.5.1",
    "google-cloud-storage>=3.2.0",
    "google-genai>=1.27.0",
    "google-generativeai>=0.8.5",
    "ipykernel>=6.29.5",
    "isort>=6.0.1",
    "matplotlib>=3.10.3",
    "nbclient>=0.10.4",
    "nbformat>=5.10.4",
    "openai>=1.97.1",
    "pandas>=2.3.1",
    "python-dotenv>=1.1.1",
    "requests>=2.32.4",
    "scikit-learn>=1.7.2",
    "seaborn>=0.13.2",
    "tiktoken>=0.9.0",
    "xai-sdk>=1.0.0",
]
